### ISSUE TITLE
Can't import any datatrove modules

### ISSUE THREAD

**Issue by griff4692** [huggingface/datatrove#102]
I have tried installing `pip install datatrove[all]` and `pip install datatrove`, as well as from source with `pip install -e .`

Yet it seems like it's not able to load any of the modules.

I'm not sure what's going on

```
>>> import datatrove.pipeline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'datatrove' has no attribute 'pipeline'
```

**Comment by shizhediao** [comment]
Hi how did you solve it? Thanks

**Comment by freemedom** [comment]
i downloaded the whl file and use this file to install it.
https://files.pythonhosted.org/packages/e5/7e/e6a07c4149899154b4ea7f6e82c2fbfe1afc4ca4f4a3bb16fc1c34e79770/datatrove-0.4.0-py3-none-any.whl

**Comment by freemedom** [comment]
ERROR: Package 'datatrove' requires a different Python: 3.9.0 not in '>=3.10.0'

**Comment by guipenedo** [comment]
Indeed we require 3.10
