### ISSUE TITLE
MinhashDedupCluster runs too slow

### ISSUE THREAD

**Issue by jordane95** [huggingface/datatrove#106]
Hi,

I find that the cluster stage in MinhashDedup runs too slow by using only one cpu to construct the union set of duplicate documents. For example, with 1T data, we can calculate the hash values in 2h with 1k cores, but the cluster stage takes more than 7h. I'm wondering whether there is any acceleration strategy for this stage.

**Comment by guipenedo** [comment]
I'll close this is there is no clear action to take here

**Comment by shizhediao** [comment]
Hi @guipenedo 
I was wondering if is it a must to use only 1 tasks for the `MinhashDedupCluster`? Can we use more tasks?

Thanks

**Comment by jordane95** [comment]
@guipenedo Hi, I find that you have updated a rust version for minhash cluster stage. I'm wondering how fast is it compared to the python implementation? Thanks.

**Comment by guipenedo** [comment]
It is incredibly fast (some workloads that would take ~2days now take 2 hours) and has a much lower memory footprint but it isn't fully deterministic (if you run multiple times different documents per cluster will be selected to be kept, always "correct" but different) and has fewer features (no index support, and there are only two versions: fully local version and fully s3 version)

**Comment by jordane95** [comment]
> It is incredibly fast (some workloads that would take ~2days now take 2 hours) and has a much lower memory footprint but it isn't fully deterministic (if you run multiple times different documents per cluster will be selected to be kept, always "correct" but different) and has fewer features (no index support, and there are only two versions: fully local version and fully s3 version)

So fast! @guipenedo I don't quiet understand why it does not support index. I haven't seen any special logic related to index in the python code (except for when setting `ignore_index_matches`). So I suspect that the rust version always remove docs that are matched with index?

**Comment by guipenedo** [comment]
With the index you just need to make sure that the index itself is never selected as the doc to be removed

**Comment by jordane95** [comment]
Actually, I run one task myself in the fully index-dedup setting (suppose the current dataset is already deduped) and find that all *.remove files have the exact same md5sum when comparing results from python code and rust code. However, there is a strange file in the output folder, 
```bash
-rw-r--r--    1 root root  49K Mar  3 17:09 001198.remove
-rw-r--r--    1 root root  98K Mar  3 17:09 001198.sizes
-rw-r--r--    1 root root  49K Mar  3 17:09 001199.remove
-rw-r--r--    1 root root  98K Mar  3 17:09 001199.sizes
-rw-r--r--    1 root root    0 Mar  3 17:09 4294967295.remove
-rw-r--r--    1 root root    8 Mar  3 17:09 4294967295.sizes
```
It might be attributed to index doc has file id = -1, which is not handled in the current code.

**Comment by guipenedo** [comment]
Ah I see you mean the index. Yes indeed we use unsigned it's so it likely just overflows because of the index (which we don't handle on rust)

**Comment by jordane95** [comment]
> With the index you just need to make sure that the index itself is never selected as the doc to be removed

I think index doc will always be placed at the left side, which means they will be always regarded as the 'parent' node so never be removed?
