### ISSUE TITLE
How to load a dataset with the output a tokenizer?

### ISSUE THREAD

**Issue by Jeronymous** [huggingface/datatrove#108]
I planned to use datatrove to apply my tokenizer so that data is ready to use with nanotron.
I am using DocumentTokenizer[Merger] which produces *.ds and *ds.index binary files, although, from what I understood, nanotron is expecting datasets (with "input_ids" keys).
I see that things like ParquetWriter cannot be piped after DocumentTokenizer.

Am I missing a piece?
Are there some helpers to convert ds files into parquet files (or something loadable with datasets) for a given context size?

**Comment by guipenedo** [comment]
Hi, I pinged the nanotron team internally and they are working on moving support of datatrove's .ds files to the public repo :)

**Comment by manuelbrack** [comment]
Following up on this: 
> Are there some helpers to convert ds files into parquet files (or something loadable with datasets) for a given context size

I was wondering the same thing. I really like datatrove, but as of now I cannot use the tokenization pipeline, since there is no way to load the data :D

**Comment by guipenedo** [comment]
Hi! Two things:
- you can always convert the text data to any format by using a writer. For instance, you can convert it to parquet using a ParquetWriter. This will convert the data with the text and not with the actual tokens, however
- I have just added a torch `Dataset` that can load tokens from a dataset tokenized by datatrove into .ds files [here](https://github.com/huggingface/datatrove/blob/main/src/datatrove/utils/dataset.py). Let me know if you would require some changes to this class for it to work with your setup

**Comment by guipenedo** [comment]
Nanotron also has support for a custom dataloader now, where you can plug in datatrove's Dataset directly: https://github.com/huggingface/nanotron/pull/162
Closing the issue

**Comment by Jeronymous** [comment]
Awesome, thanks a lot @guipenedo
