### ISSUE TITLE
Integrate readability-lxml speedup branch and Trafilatura's version of the file?

### ISSUE THREAD

**Issue by adbar** [huggingface/datatrove#117]
Hi, I see you have a commented out section in `pyproject.toml` referring to ongoing (?) work on a readability-lxml branch focusing on speedups.

I also singled out critical functions and worked on a similar project as a part of Trafilatura ([readability_lxml.py](https://github.com/adbar/trafilatura/blob/master/trafilatura/readability_lxml.py)). Since you're using the library, would you be interested in merging your progress and mine?
It could result in a PR in the Trafilatura repo or in another readability fork.

**Comment by guipenedo** [comment]
Hi! That branch (https://github.com/huggingface/python-readability/tree/speedup) is the work of @anton-l, he can provide some more details

**Comment by adbar** [comment]
A follow-up on this: I just merged my changes with some of the improvements on your side. I'll make the improved module available through Trafilatura, we can leave the issue open until then.

**Comment by anton-l** [comment]
Thank you @adbar! I never got to test exactly how much useful logic I ended up cutting, glad to see a solid integration :star_struck:

**Comment by guipenedo** [comment]
Closed as I see that you've also merged your PR on the trafilatura side
