### ISSUE TITLE
LocalExecutor Speedup 

### ISSUE THREAD

**Issue by koalazf99** [huggingface/datatrove#120]
Hi, really appreciate the project!!!

I am just wondering how I can obtain a faster local pipeline for data processing though.
For example, Can I increase `tasks` and  `workers ` to obtain faster processing? (or this will cause they handle the same piece of data?)

P.S. I am using single Node(128 CPU cores). I think I will have about 1k+ parquet files, each containing about 1M documents.

**Comment by guipenedo** [comment]
Hi! Yes, you can set `tasks=128` and the files will be distributed among your tasks (without overlap)

**Comment by koalazf99** [comment]
Cool! Thanks for your quick response! 🤗🤗🤗
