### ISSUE TITLE
Deduplicating local data throws an error

### ISSUE THREAD

**Issue by Manel-Hik** [huggingface/datatrove#142]
Hi,

I have data in my local machine in the format of a jsonl file and I want to deduplicate it. I'm using the following example:
`sent_dedup_config = SentDedupConfig(
    n_sentences=3,
    split_sentences=False,  # set to False to split on \n instead
    only_dedup_in_index=True,
    min_doc_words=50,
)

FINDER_WORKERS = 10  # this will speed up/parallelize step 2

def run_example():
    pipeline_1 = [
        JsonlReader("CC_data_inputs/"),
        SentenceDedupSignature(output_folder="cc_output/sigs", config=sent_dedup_config, finder_workers=FINDER_WORKERS),
    ]

    pipeline_2 = [SentenceFindDedups(data_folder="cc_output/sigs", output_folder="cc_output/dups", config=sent_dedup_config)]

    pipeline_3 = [
        JsonlReader(data_folder="CC_data_inputs/"),
        SentenceDedupFilter(data_folder="cc_output/dups", config=sent_dedup_config),
    ]

    executor_1: PipelineExecutor = LocalPipelineExecutor(pipeline=pipeline_1, workers=4, tasks=4)
    executor_2: PipelineExecutor = LocalPipelineExecutor(pipeline=pipeline_2, workers=1, tasks=FINDER_WORKERS)
    executor_3: PipelineExecutor = LocalPipelineExecutor(pipeline=pipeline_3, workers=4, tasks=4)

    print(executor_1.run())
    print(executor_2.run())
    print(executor_3.run())
`
I edited the first pipeline to just read the jsonl file (assuming that my data is ready directly for step 2). When I run the code, it throws this error:

Traceback (most recent call last):
  File "/home/ubuntu/deduplication/sentence_deduplication.py", line 4, in <module>
    from datatrove.pipeline.dedup.sentence_dedup import SentDedupConfig
ImportError: cannot import name 'SentDedupConfig' from 'datatrove.pipeline.dedup.sentence_dedup' (/home/ubuntu/miniconda3/lib/python3.11/site-packages/datatrove/pipeline/dedup/sentence_dedup.py)

My data consists of a set of 5 jsonl files inside the folder CC_data_inputs. I just reinstalled the datatrove library. Could you help me figure it out?

**Comment by guipenedo** [comment]
This class was added recently and is not present on the version of datatrove on pypi. Can you try cloning the repository and installing directly by running `pip install -e .` on the cloned folder?
