### ISSUE TITLE
Can a Slurm pipeline be executed across all nodes in a cluster?

### ISSUE THREAD

**Issue by hnipun** [huggingface/datatrove#162]
I've configured a Slurm cluster with one control node and two compute nodes. 

Currently, when I run the SlurmPipeline, it only utilizes resources on a single node. How can I configure it to utilize all available nodes and resources across the cluster?

Is this a configuration setting that needs adjustment within Slurm or Datatrove?

**Comment by guipenedo** [comment]
Hi! can you share the datatrove pipeline code you are currently using?

**Comment by hnipun** [comment]
```
from datatrove.pipeline.filters import SamplerFilter
from datatrove.pipeline.writers import ParquetWriter
from datatrove.pipeline.readers.parquet import ParquetReader
from datatrove.executor.base import PipelineExecutor
from datatrove.executor.slurm import SlurmPipelineExecutor

def run():
   pipeline = [
              ParquetReader('hdfs://master:9000/arxiv', text_key='txt', id_key='__id_key__'),
              SamplerFilter(rate=0.5),
              ParquetWriter(output_folder='hdfs://master:9000/slurm-test',expand_metadata=True)               
              ]
  
   executor = SlurmPipelineExecutor(pipeline=pipeline, tasks=50, time="90:00:00", partition="debug*", condaenv='test-env')
   executor.run()

if __name__ == '__main__':
  run()
```
It's a simple script. 

In the `hdfs://master:9000/arxiv/` folder, there are 20 `.parquet` files. 
One compute node has 30 cpus.

**Comment by guipenedo** [comment]
some notes:
- we do not parallelize within files, so usually you will not benefit from having tasks>nb of files in the folder (50>20)
- by default we use one cpu per task (which given the processing you are doing seems to be enough)
- how big are your nodes? since you are using 1 cpu per task and have 50 tasks (30 won't actually do anything but even assuming 50) if you have >= 50 cpus they may very well all be allocated on the same node

**Comment by hnipun** [comment]
Thanks, so if I have,

nb of files = 100
tasks = 100

will it run in both nodes, without any extra configuration ?

**Comment by guipenedo** [comment]
assuming they are both on the `debug*` partition, it should yes.
You also have to check how much memory is available on each node. By default the executor has `mem_per_cpu_gb=2`, you can adjust this option (for instance if your instances only have 1GB per cpu). Just beware that larger pipelines might require more memory

**Comment by hnipun** [comment]
Thanks, will test with much bigger dataset.

btw it's great work, with the really nice pipeline concept.  🤗
