### ISSUE TITLE
how to turn log/traceback color off?

### ISSUE THREAD

**Issue by stas00** [huggingface/datatrove#180]
Trying datatrove for the first time and the program spews a bunch of logs and tracebacks in yellow and cyan which are completely unreadable on the b&w console. 

Does the program make an assumption that the user is using w&b (dark) console?

I tried to grep for `color` to see how it controls the colors but found nothing relevant, so it's probably some 3rd party component that does that.

If the coloring logic doesn't bother to check what the console colors are to keep the output readable, any idea how to turn it off completely? I RTFM'ed - didn't find any docs that address that aspect.

Thanks a lot!

**Comment by guipenedo** [comment]
Hi,
Indeed that's an oversight on our part, we'll add an option somewhere. 
For now I think if you set the env variable `export LOGURU_COLORIZE=NO` it should disable them
Sorry about that and thank you for taking an interest in datatrove :)

**Comment by guipenedo** [comment]
For reference it's this line here with `colorize=True`:
https://github.com/huggingface/datatrove/blob/main/src%2Fdatatrove%2Futils%2Flogging.py#L46

**Comment by stas00** [comment]
I don't think it's `colorize=True`, it's the first thing I tried to set to `False` and it made no difference. I have retested it now, the color is still there. 

But `LOGURU_COLORIZE=NO` did the trick, thank you very much, @guipenedo!

It looks like even the package that caused the problem isn't documenting this feature
https://github.com/search?q=repo%3ADelgan%2Floguru%20LOGURU_COLORIZE&type=code

Would it be kindly possible to document this somewhere in this project's docs? Thank you!

**Comment by stas00** [comment]
I confirm that it works.

May I suggest that this is a sub-optimal way to implement this - as now the user has to pass this flag multiple times and the main issue is that this flag has nothing to do with the Executor but the library itself. This is a global behavior - either the user's setup can support the rainbow colors or it doesn't. It's a one-time binary decision.

Typically HF libraries have `logging.py` where logging levels and behavior is control'ed this would allow the user to set the logging behavior once at the beginning of the program and be done with it. e.g. see https://github.com/huggingface/transformers/blob/main/src/transformers/utils/logging.py
This approach works really well and ideally should belong there.

Thank you.

**Comment by guipenedo** [comment]
Very well, point taken.
I've removed the options from the executor and added the following env variables:
- `DATATROVE_COLORIZE_LOGS` "1" to add ANSI colors to console log messages and "0" to disable colorization.
- `DATATROVE_COLORIZE_LOG_FILES` set to "1" to add ANSI colors to log messages saved to logs/task_XXXXX.log.

Thank you for the taking the time to discuss this
