### ISSUE TITLE
Parallelizing Reading data from large input files

### ISSUE THREAD

**Issue by stas00** [huggingface/datatrove#183]
It looks like your fineweb setup/example relies on having many input files so it naturally gets parallelized.

However if the input is a few huge .jsonl files it currently takes forever to read them in.

Other than manually pre-splitting large files into many small ones, do you have plans on automating this process with perhaps some sort of `seek`-support so that each worker reads from a different section of the input file?

Thank you!

**Comment by hynky1999** [comment]
Yeah, it's indeed a great idea and we have this enhancement in our pipeline. See
https://github.com/huggingface/datatrove/issues/74
