### ISSUE TITLE
How to deduplicate multiple datasets?

### ISSUE THREAD

**Issue by canghaiyunfan** [huggingface/datatrove#196]
fineweb offer a deduplication  demo for one dump. If want to deduplicate more dumps, should I merge dumps before deduplication ?

**Comment by guipenedo** [comment]
if you have the data in the same folder for example `/mypath/` (even if within different subfolders `/mypath/dump1`, `/mypath/dump2`, etc) you can use `/mypath` as your input path for deduplication

**Comment by canghaiyunfan** [comment]
If the data folder as follows, I set 'DUMP_TO_PROCESS'='2013', it can't read files in  CC-MAIN-2013-20 and  CC-MAIN-2013-48  subfolders, but set 'DUMP_TO_PROCESS'='2013' is ok.
-- 2013
    |-- CC-MAIN-2013-20
    -- CC-MAIN-2013-48
