### ISSUE TITLE
Small issue on typeshelper

### ISSUE THREAD

**Issue by eurethia** [huggingface/datatrove#215]
The typeshelper.py in the package downloaded by pip install datatrove[all] does not match the repo's typeshelper. I have to edit the source code. Can the next version make sure to include all languages in Languages?
![image](https://github.com/huggingface/datatrove/assets/84611606/8e2bd52a-3d0a-47a0-8fb7-5da6f3195098)
![image](https://github.com/huggingface/datatrove/assets/84611606/7466c5c8-3558-4c34-a28e-a8e7c8c628e6)

**Comment by guipenedo** [comment]
Hi. The version on pypi is the latest stable version. For the latest dev version (the one here on github) you should clone the repository and run `pip install -e .[all]`
