### ISSUE TITLE
Standard paradigm for grouping data

### ISSUE THREAD

**Issue by UniverseFly** [huggingface/datatrove#217]
Thank you for the great library. Can I know what is a standard paradigm for grouping related data into clusters? From the Minhash example, it seems the pipeline requires dumping intermediate results into a file system. Is it the best way to do so or is it possible to do everything in memory? Also, is it possible to specify the order of the files to be read in each shard? One use case is I want to group all the documents according to a specific key, form clusters, and keep them in the original order.

Look forward to your reply!

**Comment by UniverseFly** [comment]
One follow up is when should I use datatrove or datasets. I’m having a hard time choosing the right toolchain for the use case I mentioned above.

**Comment by guipenedo** [comment]
Hi,
> Can I know what is a standard paradigm for grouping related data into clusters?

How do you want to cluster your data? N-gram similarity based like MinHash or more semantically? For semantic you can checkout this repo: https://github.com/huggingface/text-clustering

> From the Minhash example, it seems the pipeline requires dumping intermediate results into a file system. Is it the best way to do so or is it possible to do everything in memory?

Yes, this is our general approach. We designed for very large amounts of data where keeping everything in memory may not be possible.

> Also, is it possible to specify the order of the files to be read in each shard?

Files are sorted by path lexicographically and distributed into shards, see code here: https://github.com/huggingface/datatrove/blob/main/src/datatrove/io.py#L173
Grouping files into specific shards is non trivial with the current setup, the easiest way would likely be to create your own Reader subclassing one of the existing ones and override this function: https://github.com/huggingface/datatrove/blob/main/src/datatrove/pipeline/readers/base.py#L216

> One follow up question is how to choose between datatrove and datasets. I’m having a hard time choosing the right toolchain for the use case I mentioned above.

It's mostly a scale/complexity decision. If you have a small dataset and want to do basic processing using `datasets` with `.filter` or similar could be fine. If you have a larger dataset or want to perform some more advanced processing without reinventing the wheel I recommend `datatrove`

**Comment by UniverseFly** [comment]
Thank you @guipenedo for your clear and comprehensive reply. It helps me a lot in understanding the goal of datatrove.

> How do you want to cluster your data

One simple thing I want to do is to group documents that have the same values of a key together, while maintaining the relative order between the documents in the original dataset. What do you think would be the best way to achieve this?

**Comment by guipenedo** [comment]
Not sure I follow completely, could you explain a bit more the use case for this?

**Comment by UniverseFly** [comment]
Yes, for example, I have a bunch of random web documents coming from different sources (e.g. arxiv, Wikipedia, and stackoverflow). They are ordered according to when they were created. Now I want to group documents with the same source together while not breaking the chronological order.

**Comment by guipenedo** [comment]
Well, if they have a metadata field stating this source you can define it on your writer's path. See here for an example with language: https://github.com/huggingface/datatrove?tab=readme-ov-file#saving-data
You should just be careful to have the same number of tasks as the number of files you have (if you have fewer tasks than files, some tasks will process multiple files and break the order)

**Comment by UniverseFly** [comment]
Gotcha, thank you for your explanation.
