### ISSUE TITLE
Can interrupted tasks be continued?

### ISSUE THREAD

**Issue by eurethia** [huggingface/datatrove#220]
For instance, I have 10000 tasks, but the server is accidently stopped after 6000. Can the tasks be resumed?

**Comment by shizhediao** [comment]
Same question. Do we just need to rerun the script and it will automatically help us skip completed tasks and run the remaining ones?

I saw there are marks for the completed tasks.

**Comment by guipenedo** [comment]
> Same question. Do we just need to rerun the script and it will automatically help us skip completed tasks and run the remaining ones?
> 
> I saw there are marks for the completed tasks.

Yes, just relaunch with the same config/nb of tasks

**Comment by shizhediao** [comment]
Thank you very much for your confirmation!
