### ISSUE TITLE
Support for Llama 3 Tokenizer

### ISSUE THREAD

**Issue by sippycoder** [huggingface/datatrove#221]
For Llama-3 tokenizer, it currently does not support writing the tokenized file because TokenizedFile.write() uses H format which is supposed to be for `unsigned short` and throws the following error.
```
struct.error: 'H' format requires 0 <= number <= 65535
```
Should this be `I (unsigned int)` format to support with Llama-3 and Qwen-2 tokenizer?

**Comment by guipenedo** [comment]
Hi, are you using the latest pypi or the latest version on github?
On the current `main` the data type should be set automatically based on the tokenizer vocab size.

**Comment by sippycoder** [comment]
I see this code in the `main` branch, but not in the v0.2.0 version I installed with pip. I guess I should directly install from the `main` branch. Thanks!
