### ISSUE TITLE
MinhashDedup should use the language parameter

### ISSUE THREAD

**Issue by nrv** [huggingface/datatrove#234]
https://github.com/huggingface/datatrove/blob/1e27cc8819465d5246d89cd929423b76eb0bc5dd/src/datatrove/pipeline/dedup/minhash.py#L196

**Comment by pengwenzhi** [comment]
yes，because tokenizer will use it to select different language tokenizer

**Comment by guipenedo** [comment]
this has been addressed by having `word_tokenizer` be initialized based on the language
