### ISSUE TITLE
GopherQualityFilter.__init__() got an unexpected keyword argument 'language' on kaggle

### ISSUE THREAD

**Issue by williamlin0518** [huggingface/datatrove#247]
## Description

When attempting to use the `GopherQualityFilter` class, I encountered an unexpected error: `GopherQualityFilter.__init__() got an unexpected keyword argument 'language'`. This suggests that the `__init__` method of `GopherQualityFilter` does not accept a 'language' parameter, despite it being mentioned in the documentation or example code.

## Steps to Reproduce

1. Import the GopherQualityFilter class
2. Attempt to initialize GopherQualityFilter with a 'language' parameter

```python
from datatrove.pipeline.filters import GopherQualityFilter

filter = GopherQualityFilter(
    # other parameters...
    language="zh"
)
```

The documentation or example code suggests that 'language' should be a valid parameter. This discrepancy between the documentation and the actual implementation is causing confusion.
Furthermore, when inspecting the source code on Kaggle, I found that it differs from the codebase on GitHub. Here's what I did to check:
```python

from datatrove.pipeline.filters import GopherQualityFilter
import inspect
print(inspect.getsource(GopherQualityFilter))
```

C4QualityFilter also has same problem

**Comment by guipenedo** [comment]
Did you install datatrove from pypi? Can you install using `pip install git+https://github.com/huggingface/datatrove.git`? It's been a while since we've pushed a pypi release

**Comment by williamlin0518** [comment]
> Did you install datatrove from pypi? Can you install using `pip install git+https://github.com/huggingface/datatrove.git`? It's been a while since we've pushed a pypi release

ok, solved!
