### ISSUE TITLE
Option to Not Upload to Hugging Face Hub in HuggingFaceDatasetWriter

### ISSUE THREAD

**Issue by justHungryMan** [huggingface/datatrove#259]
I’ve been using HuggingFaceDatasetWriter and noticed that it seems to default to uploading to the hub when I intended to save locally only. 

Could we consider adding a parameter to prevent uploading to the hub?

**Comment by guipenedo** [comment]
Why would you use the HuggingFaceWriter if you don't want to upload to the hub? For local use you can just use the ParquetWriter, which is what the HuggingFaceWriter uses under the hood

**Comment by justHungryMan** [comment]
Occasionally, there is a need to save data in the form of a Hugging Face dataset, whether using the load_from_disk function of datasets or loading data in the hf dataset format from other libraries.

**Comment by justHungryMan** [comment]
@guipenedo 

This option is quite minor; if you think it’s unnecessary, feel free to close this issue. However, if you believe adding this feature could be beneficial, I will prepare and submit a PR.

**Comment by guipenedo** [comment]
> Occasionally, there is a need to save data in the form of a Hugging Face dataset, whether using the load_from_disk function of datasets or loading data in the hf dataset format from other libraries.

You can just use a ParquetWriter for this, it will be loadable with `load_from_disk`. This is what the huggingfacewriter uses under the hood, with the upload part on top. If you don't want to upload just use a normal `ParquetWriter`
