### ISSUE TITLE
Clarification Needed on 'Tasks' Terminology in Datatrove

### ISSUE THREAD

**Issue by eltonjohnfanboy** [huggingface/datatrove#267]
Hi everyone,

I've recently started using Datatrove for one of my personal projects and have been going through the documentation to understand it better. However, I'm having trouble understanding what is meant by "tasks." The term comes up frequently in example codes and the documentation, but I'm not quite sure what it refers to. Could someone please provide an intuitive example to help clarify this for me?

Thanks a lot!

**Comment by pengwenzhi** [comment]
the tash is your processed file count

**Comment by guipenedo** [comment]
added an explanation to the readme: https://github.com/huggingface/datatrove/blob/main/README.md#terminology
