### ISSUE TITLE
blank lines treated as duplicates in the GopherFilter

### ISSUE THREAD

**Issue by lfoppiano** [huggingface/datatrove#273]
Hi all, 
   I noticed that the gopher filter is able to recognise paragraphs and lines and make filtering based on their ratio, however, in case of processed documents is often the case that the data is surrounded by blank lines. 

Because of that, the blank lines are biasing the filter toward removing documents when the ratio passes the threshold, I was wondering whether blank lines should have a separate metric/threshold. 

What do you think?

**Comment by justHungryMan** [comment]
Wasn't this issue resolved in "https://github.com/huggingface/datatrove/commit/a8d21e2ba3bb84f721311cd7a22365fd400f0681"?

**Comment by lfoppiano** [comment]
@justHungryMan thanks! Indeed it seems this could solve the issue. I didn't mention I'm using version 0.2.0. 

I wonder whether is there a plan for a datatrove patch release?

**Comment by guipenedo** [comment]
Hi, we've just pushed version `0.3.0` to pypi, which should fix this issue :)
