### ISSUE TITLE
Question about resume mechanism

### ISSUE THREAD

**Issue by shizhediao** [huggingface/datatrove#316]
Hi,
I have a question about the resume mechanism. Suppose I have one task running while the process is broken and I have to resume it. Does the current implementation support the resume from the last status?

Thanks!

**Comment by guipenedo** [comment]
can you give some more details? can you send the pipeline you are running?
datatrove only keeps track of completed task status. It knows which tasks are completed and which aren't, and will not relaunch completed tasks, but it does not save any intermediate state for incomplete tasks, for that you can add custom logic depending on what you're doing on your blocks

**Comment by shizhediao** [comment]
Hi,
Thank you for your response. I am using the [fineweb pipeline](https://github.com/huggingface/datatrove/blob/main/examples/fineweb.py) while my input data is huge. For example, I have only one input file with 100 million docs.
The constraint of my cluster is: the compute node will be restarted every four hours. So I was wondering if datatrove could track the intermediate state.
Now I think I know the answer: It will not keep track of the intermediate state. Every time I restart, it will process that single file from scratch right? Then I might need to split it to several smaller files.

Thanks!

**Comment by guipenedo** [comment]
Exactly, my recommendation would be to split the input file into many smaller ones and run one task for each

**Comment by shizhediao** [comment]
Thank you!
