### ISSUE TITLE
replace setup.py with pyproject.toml

### ISSUE THREAD

**Issue by baggiponte** [huggingface/datatrove#54]
Hey there, glad to see there's something knew cooking with HF! I hope this project gets traction, it seems very interesting.

I noticed your setup.py is really straightforward. Its contents could simply be put inside the `pyproject.toml`: unless you are compiling C code, you won't likely need a `setup.py` to define the metadata of your package.

The biggest reason to use this format is that it's the standard that Python devs are [strongly recommended to adopt](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#is-pyproject-toml-mandatory). Practically speaking, `pyproject.toml` is a plain text file so it can be used to expose metadata about the project in PyPI, while `setup.py` needs to be run to establish them (say you have an if statement somewhere: pip does not know it by hand). This is especially useful when building wheels locally, though it should not happen on most platforms.

Using `pyproject.toml` also means that every package manager that complies with PEP518 (basically, everything but poetry) can be used to develop on this project.

Hope I was clear enough. If you are interested I'd be glad to support you 🤗

**Comment by guipenedo** [comment]
Would you be interested in making this change in a PR?

**Comment by baggiponte** [comment]
Definitely! :)
