### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [huggingface/datatrove#55]
Hi,
I noticed this project uses Trafilatura, which is GPL licensed. Would you consider switching to an alternate library such as goose3 to avoid GPL restrictions?
Thanks!

**Comment by thomwolf** [comment]
In our experiments `Trafilatura` does a great job in comparison to other extraction libraries but supporting other libraries would be very easy. Is it something you would be interested in opening a PR for?

**Comment by chschroeder** [comment]
Still, the GPL is problem here which does not disappear by adding an alternative to Trafilatura. My understanding is that datatrove needs to be licensed under the GPL now.

@adbar I mentioned this before, but in my opinion using the GPL within the Python ecosystem is not a good choice :/.

**Comment by adbar** [comment]
Hi everyone, according to the GNU website all [these licenses](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses) are compatible ("you can combine code released under the other license with code released under the GNU GPL in one larger program").

Datatrove is obviously a larger program and its license (Apache 2.0) is compatible.

@chschroeder So it's not true that another package needs to use the GPL, a modified version of Trafilatura would but it's not what is at stake here.

**Comment by chschroeder** [comment]
This just means that you can mix GPL-licensed code with code that is released under one of the free licenses listed at the linked page (such as Apache 2.0). The combined work is still GPL. 

Either way, I am not a lawyer, but I avoid GPL code for my Python projects for exactly that reason.

**Comment by adbar** [comment]
Thanks for drawing my attention to this issue, the [doc page](https://www.gnu.org/licenses/gpl-faq.html#GPLPlugins) is unclear on this point.

> If the main program dynamically links plug-ins, but the communication between them is limited to invoking the
> ‘main’ function of the plug-in with some options and waiting for it to return, that is a borderline case.

That's the case here. I also found [this post](https://tech.popdata.org/the-gpl-license-and-linking-still-unclear-after-30-years/) on a similar problem among the R community.

It is not my intention to prevent Huggingface from integrating Trafilatura in their packages. If it is a problem I could consider a change of license or dual licensing for future versions.

**Comment by fakerybakery** [comment]
Hi,
I'm not a lawyer but do you know if it's possible to just make the Trafilatura plugin GPL licensed, and perhaps separate it into another package? AFAIK I'm pretty sure I could go make another filter in a separate package that uses DataTrove and GPL license it - do you know if that's possible?

**Comment by adbar** [comment]
I don't know how that would work if the existing solution doesn't already work: either packages under different licenses can be linked or they can't.

In the R community the GPL license is much more common and things are handled differently. Also, your use case is a borderline one according to the GNU itself so I don't believe there could be a major problem here.

If a substantial amount of doubt subsists I'll think about it and come up with a solution.

**Comment by adbar** [comment]
I plan to change the license so the situation should get clearer for everyone involved, see the progress in https://github.com/adbar/trafilatura/issues/512.

**Comment by guipenedo** [comment]
Thank you @adbar, indeed that would greatly simplify things.

**Comment by guipenedo** [comment]
Now using the new apache2 version of trafilatura :)
