### ISSUE TITLE
Wrong `docstring` in `UnigramLogProbFilter`

### ISSUE THREAD

**Issue by IlievskiV** [huggingface/datatrove#64]
The class `docstirng` here refers to the `LanguageFilter` and should be updated:

https://github.com/huggingface/datatrove/blob/463c2a352d20c9972a0bb2434abafb434cf5df01/src/datatrove/pipeline/filters/unigram_log_probs.py#L27

**Comment by guipenedo** [comment]
Thanks for reporting! Will be fixed in #65
