### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by IlievskiV** [huggingface/datatrove#66]
Hi, on this line a `ZeroDivisionError` is raised:

![image](https://github.com/huggingface/datatrove/assets/4522582/0dff53bd-f00b-4e5b-9bf4-59b7ac758d29)

https://github.com/huggingface/datatrove/blob/463c2a352d20c9972a0bb2434abafb434cf5df01/src/datatrove/pipeline/filters/unigram_log_probs.py#L62

**Comment by NicholasLindner** [comment]
Hi! Can I get this task assigned to me?

**Comment by guipenedo** [comment]
Sure :)

**Comment by guipenedo** [comment]
@NicholasLindner any news on this? should be a simple fix (just check if `len(freqs)` is 0 and if so just return 0 instead)

**Comment by NicholasLindner** [comment]
Yes, I have time today to work on it. I got caught up with something yesterday. I will do it

**Comment by NicholasLindner** [comment]
@guipenedo Just finished making the changes. However, when I try to push the changes after committing, I get a permissions error, shown in the image. I tried both push --set-upstream origin and just push origin, but both have the same result. Is the issue that I created a new branch? If so, what should I do? Thank you so much!

**Comment by guipenedo** [comment]
Hi, you should create a fork and make your changes in your fork. You can then create a Pull request on GitHub to have your fork merged onto datatrove. You can see more info [here](https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project)

**Comment by NicholasLindner** [comment]
Done! Thanks!

**Comment by guipenedo** [comment]
Fixed in #71
