### ISSUE TITLE
Writer adapter

### ISSUE THREAD

**Issue by jordane95** [huggingface/datatrove#77]
Do you think it is a good idea to also add a writer adapter for the jsonl writer?

The reader also has this functionality which greatly improves the flexibility when working with jsonl data with different keys.

**Comment by guipenedo** [comment]
Can you give me a specific use case?

**Comment by jordane95** [comment]
I'm using a different format of json as training data. The structure is a little different from the format used in datatrove. The output of the current writer cannot directly fit in my latter pipeline.

For example, we may want to use the key 'meta' instead of 'metadata' and add a 'version' field to denote the version of the data.

**Comment by guipenedo** [comment]
Makes sense, will add

**Comment by guipenedo** [comment]
Please let me know if this is what you'd like @jordane95 #83
