### ISSUE TITLE
Multi-node parallelism

### ISSUE THREAD

**Issue by jordane95** [huggingface/datatrove#80]
To process extreme large datasets efficiently with local cpu clusters, it would be more efficient to run the processing code on multiple machines, where each machine can process its own tasks via multiple workers.

Do you think it is possible to add such features? Or is this redundant?

**Comment by guipenedo** [comment]
It is quite easy to add, but aren't these machines networked together or behind some sort of cluster?

**Comment by jordane95** [comment]
Yes, but I'm interacting with machines at a bit low-level, where each machine essentially launch the code independently and is indexed by the global rank and world size defined by environment variables.

Let's say we have a total of 10000 cores, distributed on 100 machines each with 100 cpus. We need to assign each machine with > 100 tasks to keep the core busy but we cannot directly launch 10000 tasks with the current code using the `LocalPipelineExecutor`, since `mg.Queue()` on each machine is un-aware of others' existence. I'm thinking about adding an additional pair of global (rank, world_size) while reading and writing files, but this would involve changing many functions in the pipeline dir.

**Comment by guipenedo** [comment]
Very well, I'll make some changes today

**Comment by guipenedo** [comment]
Mind giving #85 a try?

**Comment by jordane95** [comment]
Works well!
