### ISSUE TITLE
Tokenization for Non English data

### ISSUE THREAD

**Issue by Manel-Hik** [huggingface/datatrove#93]
Hi HF team
I want to thank you for this incredible work.
And I have a question, I want to apply pipeline of deduplication for Arabic data.
 For this  I should change the tokenizer I think, And if yes is there a tip for this, 
for this should I just edit the tokenizer here
`class SentenceDedupFilter(PipelineStep):
    type = "🫂 - DEDUPS"
    name = "💥 sentence-deduplication stage 3"

    def __init__(
        self,
        data_folder: DataFolderLike,
        n_sentences: int = 3,
        min_doc_words: int = 50,
        exclusion_writer: DiskWriter = None,
    ):
        """Args:
        data_folder: data folder to get duplicate files.
        min_doc_words: min amount of words for each document
        """
        from nltk import load

        super().__init__()
        self.data_folder = get_datafolder(data_folder)
        self.n_sentences = n_sentences
        self.min_doc_words = min_doc_words
        **self._tokenizer = load("tokenizers/punkt/english.pickle")**
        self.exclusion_writer = exclusion_writer`
        
        
any recommendations please?
Thanks

**Comment by guipenedo** [comment]
Hi!
I've added support for a `language` parameter: https://github.com/huggingface/datatrove/pull/94/

Unfortunately, it seems that arabic is not supported directly by nltk: https://github.com/alyssaq/nltk_data/blob/master/tokenizers/punkt/README

What I suggest you do is test the following code (which should separate text into sentences) with some examples:
```python
from nltk import sent_tokenize
print(sent_tokenize("some text. another sentence?"))
```

If it doesn't really work you can try replacing other sentence boundary characters (I'm not an arabic speaker so I am not sure about which characters there would be) and replace them with english sentence boundary characters ("?", "!", etc) and after deduplication revert it

I'd appreciate it if you could let me know afterwards what approach you end up choosing
