### ISSUE TITLE
Job depends in local executor

### ISSUE THREAD

**Issue by jordane95** [huggingface/datatrove#97]
I find that the job depends in slurm executor very useful in running messy jobs with a lot of stages like minhash deduplication. But it seems that current local executor doesn't support this functionality, especially in the multi-node setting. Is it possible to integrate this feature for local executor as well?

**Comment by guipenedo** [comment]
This works locally by having the multiple stages on the same script.
Running with multi node indeed there is the additional problem of having to synchronize the job end. What `logging_dir` are you using? Something local to each node or a cloud path accessible from all the nodes?

**Comment by jordane95** [comment]
I'm using a storage where all nodes share the same logging dir

**Comment by guipenedo** [comment]
Can you check #100 ?
